/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Abdelrahman Khaled
 */
public class StochasticInputScreen extends javax.swing.JFrame {

    /**
     * Creates new form StochasticInputScreen
     */
    public StochasticInputScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleP1 = new javax.swing.JLabel();
        physicalNumberOfServers = new javax.swing.JComboBox<>();
        titleP2 = new javax.swing.JLabel();
        systemCapacity = new javax.swing.JComboBox<>();
        titleP3 = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        titleP1.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        titleP1.setForeground(new java.awt.Color(50, 50, 50));
        titleP1.setText("M / M /");

        physicalNumberOfServers.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        physicalNumberOfServers.setForeground(new java.awt.Color(50, 50, 50));
        physicalNumberOfServers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "c" }));

        titleP2.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        titleP2.setForeground(new java.awt.Color(50, 50, 50));
        titleP2.setText("/");

        systemCapacity.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        systemCapacity.setForeground(new java.awt.Color(50, 50, 50));
        systemCapacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "∞", "K" }));
        systemCapacity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        systemCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemCapacityActionPerformed(evt);
            }
        });

        titleP3.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        titleP3.setForeground(new java.awt.Color(50, 50, 50));
        titleP3.setText("/ FCFS");

        enter.setFont(new java.awt.Font("Gabriola", 1, 26)); // NOI18N
        enter.setForeground(new java.awt.Color(0, 0, 130));
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Gabriola", 1, 26)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 0, 130));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleP1)
                        .addGap(0, 0, 0)
                        .addComponent(physicalNumberOfServers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(titleP2)
                        .addComponent(systemCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(titleP3)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleP2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(systemCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleP3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(physicalNumberOfServers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleP1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        if(physicalNumberOfServers.getSelectedIndex() == 0 && systemCapacity.getSelectedIndex() == 0)
        {
            M_M_1InputScreen screen = new M_M_1InputScreen();
            screen.setLocationRelativeTo(null);
            screen.setVisible(true);
        }
        else if(physicalNumberOfServers.getSelectedIndex() == 0 && systemCapacity.getSelectedIndex() == 1)
        {
            M_M_1_KInputScreen screen = new M_M_1_KInputScreen();
            screen.setLocationRelativeTo(null);
            screen.setVisible(true);
        }
        else if(physicalNumberOfServers.getSelectedIndex() == 1 && systemCapacity.getSelectedIndex() == 0)
        {
            M_M_cInputScreen screen = new M_M_cInputScreen();
            screen.setLocationRelativeTo(null);
            screen.setVisible(true);
        }
        else
        {
            M_M_c_KInputScreen screen = new M_M_c_KInputScreen();
            screen.setLocationRelativeTo(null);
            screen.setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_enterActionPerformed

    private void systemCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_systemCapacityActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        StartScreen screen = new StartScreen();
        screen.setLocationRelativeTo(null);
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StochasticInputScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StochasticInputScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StochasticInputScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StochasticInputScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StochasticInputScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton enter;
    private javax.swing.JComboBox<String> physicalNumberOfServers;
    private javax.swing.JComboBox<String> systemCapacity;
    private javax.swing.JLabel titleP1;
    private javax.swing.JLabel titleP2;
    private javax.swing.JLabel titleP3;
    // End of variables declaration//GEN-END:variables
}
